name: Deployment

on:
  push:
    branches: [master] # push events on source branch master push

jobs:
  islander-forum-system-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Golang Action
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
    - run: go version

    - name: Build Application
      run: |
        go env -w GOOS=linux
        go build
    
    - name: Publish
      uses: nogsantos/scp-deploy@master
      with:
        src: ./forum_server
        host: ${{ secrets.SSH_HOST }}
        remote: ${{ secrets.SSH_DIR }}
        # port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}

    # - name: Set SSH Key
    #   uses: webfactory/ssh-agent@v0.1.1
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_KEY }}

    # - name: Setup knownhosts
    #   run: ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Add SSH key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p /home/runner/.ssh
        # Replace example.com with the hostname of the machine
        # you're SSH-ing into
        ssh-keyscan ${{ secrets.SSH_HOST }} >> /home/runner/.ssh/known_hosts
        # DOKKU_SSH_KEY is the name of the repository secret
        echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
        chmod 600 /home/runner/.ssh/github_actions
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
        ssh-add /home/runner/.ssh/github_actions

    - name: Start Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_DIR }}/..; ls -al"
