name: Deployment

on:
  push:
    branches: [master] # push events on source branch master push

jobs:
  islander-forum-system-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Golang Action
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
    - run: go version

    - name: Build Application
      run: |
        go env -w GOOS=linux
        go build
    
    - name: Publish
      uses: nogsantos/scp-deploy@master
      with:
        src: ./forum_server
        host: ${{ secrets.SSH_HOST }}
        remote: ${{ secrets.SSH_DIR }}
        # port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
